### ISSUE TITLE
nodent-runtime missing dependency when using module with npm

### ISSUE THREAD

**Issue by jlengrand** [smeijer/leaflet-geosearch#111]
Hi there, 

I have installed the dependency as mentioned in your README

```
$ npm install --save leaflet-geosearch
```

Trying to then compile using webpack leads to this error : 

```
ERROR in ../~/leaflet-geosearch/lib/leafletControl.js
Module not found: Error: Can't resolve 'nodent-runtime' in 'C:\Users\jleng\Work\SkyAi\warm-website\node_modules\leaflet-geosearch\lib'
 @ ../~/leaflet-geosearch/lib/leafletControl.js 7:21-46
 @ ../~/leaflet-geosearch/lib/index.js
 @ ./skyai.js
```

Indeed your provider.js file mentions 

`var _nodentRuntime = require('nodent-runtime');`

Running 
```
$ npm install --save nodent-runtime
```

seems to solve the issue. 

Could it be that your package.json should include nodent-runtime as a dependency? (I see it in the require part of the json file but it did not seem to prevent the error on my system.

Cheers

**Comment by smeijer** [comment]
Fixed by #112

**Comment by alexrussell** [comment]
I'm not sure this is fixed by #112. That PR adds the dep to devDependencies, but this is required in the 'normal' dependencies, right?

**Comment by alexrussell** [comment]
Oh actually it looks like `nodent-runtime` is only required in the webpack build, so devDependencies is fine. Oddly though, I'm getting the issue of `nodent-runtime` not being found in actual use. NPM only contains version 2.0.3 at the moment (can't get 2.1.0) so I dunno if that's a possible issue.

**Comment by jlengrand** [comment]
@alexrussell That's what I have experienced. nodent-runtime is only needed for building.

What do you mean by actual use? It still can't be found during your npm install? Which version of node are you using? LTS? It might be the issue, since I am using latest stable.

**Comment by alexrussell** [comment]
@jlengrand to be honest I have 'given up' on this package, as I don't even need a control - just a quick easy way to geocode a search term.

However, for your reference I have a React project that I am using Leaflet with, so I simply ran `yarn add leaflet-geosearch` to install this library it as a runtime dep (which doesn't install `nodent-runtime` as it's a dev dependency of this package (though, because I'm on 2.0.3 it's not even in the `package.json` anyway as this was only added recently, but that's beside the point). Upon compilation of my app using webpack, I get this `nodent` issue.

At a guess, some stuff changed between 2.0.3 and 2.1.0 that stops `nodent-runtime` being used in the actual runtime code, so the PR you submitted is probably fine.

**Comment by jlengrand** [comment]
Alright, thanks for the info. I have dropped leaflet-geosearch earlier today as well, but it still might be interesting for reference for future users :). 
Thanks for the extra bits of info.

**Comment by smeijer** [comment]
I reopened the issue. If there are still problems with this runtime, than it must be fixed.

@alexrussell It's sad to hear you've given up on this project. Especially since this library should make it very easy to only use the provider you need, without the entire control. As that is what you need.

@jlengrand Can I ask what library you're now using instead?

**Comment by jlengrand** [comment]
@smeijer Nothing! I'm super happy about this library, but to get as simple as possible we decided to let go with the geosearch in the end. 
I'll use it again for sure next time I am searching for something similar. 

Regarding the nodent issue. Could we not change the PR so that it needs **a** version of nodent-runtime rather than a specific version? That should fix it for everbody, shouldn't it?

**Comment by alexrussell** [comment]
@smeijer yeah I agree that this library is small enough but provides (or at least appears to provide) the right kind of functionality for my purpose. Unfortunately, right now I just need to get moving with this project so can't really afford the time to be messing with deps that don't work quite right.

I will be moving onto a new library today, but I haven't decided which yet. Being as I only need the geocoding ability, my candidates are (chosen from nominatim clients on npm, filtered to those that don't have huge dependencies):

- `demsking/nominatim-client`
- `andrewlively/nodinatim`

I tried `patcurry/easy-nominatim` yesterday but found in the end that 1. it lacked 'how to use' docs (luckily I got how to use it) which is not ideal 2. it uses callbacks rather than promises (oddly, internally it turns XHR into a promise, but then uses a callback on the 'public' API for some reason) and most importantly 3. it does no transformation of the JSON that comes back (in fact it doesn't even appear to parse the JSON, just returning the response text. I could really do with a lib that gives me lat/lng in an easy-to-digest form.

**Comment by alexrussell** [comment]
@smeijer if you want to publish 2.1.0 to NPM I can give it a go today, we may find that the dependency issue has been fixed since 2.0.3.

**Comment by smeijer** [comment]
@alexrussell Okay; I understand. And I must admit that I would do the same when I install some lib that doesn't "just work".

I've published `2.1.0`.  Hope you can try that one.

Also @jlengrand opened a PR #115 , I plan to merge that one today as well. Hoping it makes things better for you guys. As I said, I cannot test this one; as I'm not experiencing these issues. So for me it's just trial and error, and act on your feedback.

Thanks for sticking with this project (and me) !

**Comment by jlengrand** [comment]
@smeijer No worries, it is a pleasure. 

I have beens earching for (small) libraries related to GIS that I could contribute to. This is minimal but a start :).

Do let me know if there are other things I can assist with.

**Comment by alexrussell** [comment]
Okay I have installed 2.1.0 and still getting the nodent missing module issue. I'm gonna quickly see what's going on.

**Comment by alexrussell** [comment]
Okay that was quick, I can see exactly what's going on - the `lib` version uses `nodent-runtime` so you need to put it in the `dependencies` not `devDependencies` part of the package's `package.json`.

Out of interest, what *is* nodent-runtime and what's it used for?

**Comment by alexrussell** [comment]
Okay I can see now that nodent-runtime is a package that allows for `async`/`await` in code that you include in the `entry` of the webpack config. So while it's not required directly, it does need to be around in order for your code to work.

My advice would be (and I am in no way a master of JS libraries) that the UMD/ES5 (dist) build should probably bundle and use nodent-runtime) but the CJS (lib) probably shouldn't. For example, I am using babel with the various presets and plugins that allow me to use async/await in my code without using `nodent-runtime`, so even if you *did* include it in the non-dev-deps of your package, including it would be somewhat wasteful for me.

I guess you need to make a decision on your audience and whether you wish to demand that they *somehow* sort out async/await for your package, or bundle something in that does it for them, albeit wastefully in situations where they already have support for this.

The best plan would be to probably remove the reliance on this package by turning your async functions (there are only a few in the whole codebase) into regular promise-based ones. But, of course, that does involve potentially compromising your own dev experience for the lowest common factor.

**Comment by smeijer** [comment]
Actually that should exactly be what's happening. The `dist` bundle includes the runtime. I chose for `nodent-runtime` instead of a `babel polyfill` because of it's smaller byte size. In bigger projects I also use the babel stuff. I just dit not like the idea that the polyfill in the bundle became bigger than the actual code.

I don't like the idea of changing `async` statements it to `promisses`, as we then get a similar issue with browsers not supporting promises natively.

So, what are you suggesting? Update the readme to make clear that the project is written with ES6 in mind, and that developers need to transpile the code to support `async / await` statements, and include a `fetch` polyfill for browsers not supporting fetch?

**Comment by smeijer** [comment]
Aaah, I understand. The `bundle` does indeed include `nodent-runtime`, and the `lib` does not. But the `lib` does have `require('nodent-runtime')` statements, causing the bug.

It all makes sense now.

**Comment by alexrussell** [comment]
@smeijer I'm not specifically suggesting anything, but yeah I think your options are:

- Support ES5 environments only (remove reliance on promises, async, fetch, etc.)
- Require an ES6 environment (you can use promises and fetch, but not async unless you specify that it's ES6 + stage-4 or ES2017 as far as I know) and tell the library users that they must provide for these things you use (with a fetch/promise/generator polyfill and syntax transpilation for async/await)

As for the UMD/CJS current situation, what you say is not (quite) what's happening then. Ahh just seen your latest comment and yes you have the story right.

**Comment by smeijer** [comment]
Okay; I've decided to include the `nodent-runtime` as normal `dependency`. Although I do agree that it sucks that some users now have a double `async` transformer. I think it is the best way to go.

I've consciously chosen for the `nodent-runtime` over a `babel-transformer` because of the bytesize, and performance. Documentation of that project can be found here: https://github.com/MatAtBread/nodent

This issue should be fixed now; as can be seen here: [failing 2.1.1][1] and [working 2.2.0][2]

[1]: https://runkit.com/smeijer/leaflet-geosearch-issue--111/v2.1.0
[2]: https://runkit.com/smeijer/leaflet-geosearch-issue--111/v2.2.0

@alexrussell , are you willing to try the `2.2.0` version? Should work without any troubles now.

**Comment by smeijer** [comment]
Also; I do think we should update the docs to be clear about ES6 ES2017 syntax and required polyfills to support older browsers.

**Comment by alexrussell** [comment]
@smeijer in the end I just made myself a very simple function to do the OSM geocoding as no library out there that I tried (filtering out ones that are node-specific or with dependencies like bluebird, etc.) actually returns a promise I can use. In the end I have a fetch polyfill and generator/async transforms in place, so I just made a quick fetching function and JSON mapper.

However, FWIW I have just tried 2.2.0 and it works as expected.

**Comment by smeijer** [comment]
Thanks for the feedback 😄  You do know that the provider here returns a promise?

```js
const { OpenStreetMapProvider } = require('leaflet-geosearch@2.2.0');

const provider = new OpenStreetMapProvider();
const result = await provider.search({ query: 'leeuwarden, netherlands' }); 
result[0].raw;
```

or 

```js
const { OpenStreetMapProvider } = require('leaflet-geosearch@2.2.0');

const provider = new OpenStreetMapProvider();
provider.search({ query: 'leeuwarden, netherlands' }).then(results => {
  results[0].raw;
});
```

But I understand that sometimes a simple mapper can be all you need. Closing this issue, as it seems to be fixed.

**Comment by alexrussell** [comment]
@smeijer ahh yes, your package was the exception here - while I was waiting for an answer on the nodent/no-nodent issue I did my simple thing and to be honest am pretty happy with it so I'm gonna stick with it. Plus I'd rather not bundle nodent as well as my Babel-based transform.
